import { NEIGHBORHOOD_POPULATE_FIELDS } from "@/types/neighborhood";

export const NEIGHBORHOOD_POPULATABLE_FIELDS = [
  NEIGHBORHOOD_POPULATE_FIELDS.AGENT,
  NEIGHBORHOOD_POPULATE_FIELDS.IMAGES,
  NEIGHBORHOOD_POPULATE_FIELDS.MAIN_IMAGE,
  NEIGHBORHOOD_POPULATE_FIELDS.LOGO,
  NEIGHBORHOOD_POPULATE_FIELDS.PROPERTIES,
];
