import { PROPERTY_POPULATE_FIELDS } from "@/types/property";

export const PROPERTY_POPULATABLE_FIELDS = [PROPERTY_POPULATE_FIELDS.AGENT, PROPERTY_POPULATE_FIELDS.IMAGES, PROPERTY_POPULATE_FIELDS.MAIN_IMAGE];